// Field aliases for enhanced query processing
// Auto-generated from actual endpoint data fields
// Generated: 2025-09-02T12:05:31.883Z
// Total fields: 268 from 52 endpoints
export const FIELD_ALIASES: Record<string, string> = {
  // === SYSTEM FIELDS ===
  "creationdate": "CreationDate",
  "creation date": "CreationDate",
  "creator": "Creator",
  "description": "DESCRIPTION",
  "d e s c r i p t i o n": "DESCRIPTION",
  "editdate": "EditDate",
  "edit date": "EditDate",
  "editor": "Editor",
  "id": "ID",
  "i d": "ID",
  "objectid": "OBJECTID",
  "o b j e c t i d": "OBJECTID",
  "shape__area": "Shape__Area",
  "shape   area": "Shape__Area",
  "shape__length": "Shape__Length",
  "shape   length": "Shape__Length",
  "thematic value": "thematic_value",
  // === ANALYSIS SCORE FIELDS ===
  "algorithm agreement score": "algorithm_agreement_score",
  "algorithm agreement": "algorithm_agreement_score",
  "algorithm comparison score": "algorithm_comparison_score",
  "algorithm comparison": "algorithm_comparison_score",
  "algorithm performance score": "algorithm_performance_score",
  "algorithm performance": "algorithm_performance_score",
  "algorithm reliability score": "algorithm_reliability_score",
  "algorithm reliability": "algorithm_reliability_score",
  "algorithm suitability score": "algorithm_suitability_score",
  "algorithm suitability": "algorithm_suitability_score",
  "alternative algorithm score": "alternative_algorithm_score",
  "alternative algorithm": "alternative_algorithm_score",
  "analysis score": "analysis_score",
  "analysis": "analysis_score",
  "anomaly insight score": "anomaly_insight_score",
  "anomaly insight": "anomaly_insight_score",
  "anomaly insights score": "anomaly_insights_score",
  "anomaly insights": "anomaly_insights_score",
  "anomaly performance score": "anomaly_performance_score",
  "anomaly performance": "anomaly_performance_score",
  "anomaly reliability score": "anomaly_reliability_score",
  "anomaly reliability": "anomaly_reliability_score",
  "anomaly score": "anomaly_score",
  "anomaly": "anomaly_score",
  "anomaly significance score": "anomaly_significance_score",
  "anomaly significance": "anomaly_significance_score",
  "behavioral score": "behavioral_score",
  "behavioral": "behavioral_score",
  "best algorithm confidence score": "best_algorithm_confidence_score",
  "best algorithm confidence": "best_algorithm_confidence_score",
  "brand difference score": "brand_difference_score",
  "brand difference": "brand_difference_score",
  "cluster score": "cluster_score",
  "cluster": "cluster_score",
  "comparison score": "comparison_score",
  "comparison": "comparison_score",
  "competitive score": "competitive_score",
  "competitive": "competitive_score",
  "component significance score": "component_significance_score",
  "component significance": "component_significance_score",
  "consensus analysis score": "consensus_analysis_score",
  "consensus analysis": "consensus_analysis_score",
  "consensus confidence score": "consensus_confidence_score",
  "consensus confidence": "consensus_confidence_score",
  "consensus performance score": "consensus_performance_score",
  "consensus performance": "consensus_performance_score",
  "consensus score": "consensus_score",
  "consensus": "consensus_score",
  "correlation score": "correlation_score",
  "correlation": "correlation_score",
  "customer profile score": "customer_profile_score",
  "customer profile": "customer_profile_score",
  "data complexity score": "data_complexity_score",
  "data complexity": "data_complexity_score",
  "demographic insights score": "demographic_insights_score",
  "demographic insights": "demographic_insights_score",
  "demographic score": "demographic_score",
  "demographic": "demographic_score",
  "dimensionality insights score": "dimensionality_insights_score",
  "dimensionality insights": "dimensionality_insights_score",
  "dimensionality performance score": "dimensionality_performance_score",
  "dimensionality performance": "dimensionality_performance_score",
  "dimensionality reduction benefit score": "dimensionality_reduction_benefit_score",
  "dimensionality reduction benefit": "dimensionality_reduction_benefit_score",
  "dimensionality score": "dimensionality_score",
  "dimensionality": "dimensionality_score",
  "ensemble analysis score": "ensemble_analysis_score",
  "ensemble analysis": "ensemble_analysis_score",
  "ensemble confidence score": "ensemble_confidence_score",
  "ensemble confidence": "ensemble_confidence_score",
  "ensemble opportunity score": "ensemble_opportunity_score",
  "ensemble opportunity": "ensemble_opportunity_score",
  "ensemble performance score": "ensemble_performance_score",
  "ensemble performance": "ensemble_performance_score",
  "ensemble reliability score": "ensemble_reliability_score",
  "ensemble reliability": "ensemble_reliability_score",
  "ensemble strength score": "ensemble_strength_score",
  "ensemble strength": "ensemble_strength_score",
  "feature compression score": "feature_compression_score",
  "feature compression": "feature_compression_score",
  "feature importance clarity score": "feature_importance_clarity_score",
  "feature importance clarity": "feature_importance_clarity_score",
  "feature relationship strength score": "feature_relationship_strength_score",
  "feature relationship strength": "feature_relationship_strength_score",
  "importance score": "importance_score",
  "importance": "importance_score",
  "interaction score": "interaction_score",
  "interaction": "interaction_score",
  "interpretability benefit score": "interpretability_benefit_score",
  "interpretability benefit": "interpretability_benefit_score",
  "investigation priority score": "investigation_priority_score",
  "investigation priority": "investigation_priority_score",
  "lifestyle score": "lifestyle_score",
  "lifestyle": "lifestyle_score",
  "market anomaly value score": "market_anomaly_value_score",
  "market anomaly value": "market_anomaly_value_score",
  "market context score": "market_context_score",
  "market context": "market_context_score",
  "model agreement score": "model_agreement_score",
  "model agreement": "model_agreement_score",
  "model component strength score": "model_component_strength_score",
  "model component strength": "model_component_strength_score",
  "model diversity benefit score": "model_diversity_benefit_score",
  "model diversity benefit": "model_diversity_benefit_score",
  "model performance prediction score": "model_performance_prediction_score",
  "model performance prediction": "model_performance_prediction_score",
  "model selection performance score": "model_selection_performance_score",
  "model selection performance": "model_selection_performance_score",
  "model selection score": "model_selection_score",
  "model selection": "model_selection_score",
  "multi model value score": "multi_model_value_score",
  "multi model value": "multi_model_value_score",
  "opportunity detection score": "opportunity_detection_score",
  "opportunity detection": "opportunity_detection_score",
  "outlier score": "outlier_score",
  "outlier": "outlier_score",
  "outlier strength score": "outlier_strength_score",
  "outlier strength": "outlier_strength_score",
  "performance score": "performance_score",
  "performance": "performance_score",
  "prediction consensus score": "prediction_consensus_score",
  "prediction consensus": "prediction_consensus_score",
  "prediction precision score": "prediction_precision_score",
  "prediction precision": "prediction_precision_score",
  "prediction reliability score": "prediction_reliability_score",
  "prediction reliability": "prediction_reliability_score",
  "prediction score": "prediction_score",
  "prediction": "prediction_score",
  "r2 score": "r2_score",
  "r2": "r2_score",
  "recommendation confidence score": "recommendation_confidence_score",
  "recommendation confidence": "recommendation_confidence_score",
  "scenario score": "scenario_score",
  "scenario": "scenario_score",
  "segment score": "segment_score",
  "segment": "segment_score",
  "selection reliability score": "selection_reliability_score",
  "selection reliability": "selection_reliability_score",
  "sensitivity score": "sensitivity_score",
  "sensitivity": "sensitivity_score",
  "strategic score": "strategic_score",
  "strategic": "strategic_score",
  "strategic value score": "strategic_value_score",
  "strategic value": "strategic_value_score",
  "trend score": "trend_score",
  "trend": "trend_score",
  "uncertainty quantification score": "uncertainty_quantification_score",
  "uncertainty quantification": "uncertainty_quantification_score",
  "voting consensus strength score": "voting_consensus_strength_score",
  "voting consensus strength": "voting_consensus_strength_score",
  // === MP CODES (Current Project Data Fields) ===
  "mp10002a_b": "MP10002A_B",
  "m p10002 a  b": "MP10002A_B",
  "mp10002": "MP10002A_B",
  "mp10002a_b_p": "MP10002A_B_P",
  "m p10002 a  b  p": "MP10002A_B_P",
  "mp10020a_b": "MP10020A_B",
  "m p10020 a  b": "MP10020A_B",
  "mp10020": "MP10020A_B",
  "mp10020a_b_p": "MP10020A_B_P",
  "m p10020 a  b  p": "MP10020A_B_P",
  "mp10028a_b": "MP10028A_B",
  "m p10028 a  b": "MP10028A_B",
  "mp10028": "MP10028A_B",
  "mp10028a_b_p": "MP10028A_B_P",
  "m p10028 a  b  p": "MP10028A_B_P",
  "mp10104a_b": "MP10104A_B",
  "m p10104 a  b": "MP10104A_B",
  "mp10104": "MP10104A_B",
  "mp10104a_b_p": "MP10104A_B_P",
  "m p10104 a  b  p": "MP10104A_B_P",
  "mp10110a_b": "MP10110A_B",
  "m p10110 a  b": "MP10110A_B",
  "mp10110": "MP10110A_B",
  "mp10110a_b_p": "MP10110A_B_P",
  "m p10110 a  b  p": "MP10110A_B_P",
  "mp10116a_b": "MP10116A_B",
  "m p10116 a  b": "MP10116A_B",
  "mp10116": "MP10116A_B",
  "mp10116a_b_p": "MP10116A_B_P",
  "m p10116 a  b  p": "MP10116A_B_P",
  "mp10120a_b": "MP10120A_B",
  "m p10120 a  b": "MP10120A_B",
  "mp10120": "MP10120A_B",
  "mp10120a_b_p": "MP10120A_B_P",
  "m p10120 a  b  p": "MP10120A_B_P",
  "mp10128a_b": "MP10128A_B",
  "m p10128 a  b": "MP10128A_B",
  "mp10128": "MP10128A_B",
  "mp10128a_b_p": "MP10128A_B_P",
  "m p10128 a  b  p": "MP10128A_B_P",
  "mp10138a_b": "MP10138A_B",
  "m p10138 a  b": "MP10138A_B",
  "mp10138": "MP10138A_B",
  "mp10138a_b_p": "MP10138A_B_P",
  "m p10138 a  b  p": "MP10138A_B_P",
  "mp12097a_b": "MP12097A_B",
  "m p12097 a  b": "MP12097A_B",
  "mp12097": "MP12097A_B",
  "mp12097a_b_p": "MP12097A_B_P",
  "m p12097 a  b  p": "MP12097A_B_P",
  "mp12205a_b": "MP12205A_B",
  "m p12205 a  b": "MP12205A_B",
  "mp12205": "MP12205A_B",
  "mp12205a_b_i": "MP12205A_B_I",
  "m p12205 a  b  i": "MP12205A_B_I",
  "mp12205a_b_p": "MP12205A_B_P",
  "m p12205 a  b  p": "MP12205A_B_P",
  "mp12206a_b": "MP12206A_B",
  "m p12206 a  b": "MP12206A_B",
  "mp12206": "MP12206A_B",
  "mp12206a_b_i": "MP12206A_B_I",
  "m p12206 a  b  i": "MP12206A_B_I",
  "mp12206a_b_p": "MP12206A_B_P",
  "m p12206 a  b  p": "MP12206A_B_P",
  "mp12207a_b": "MP12207A_B",
  "m p12207 a  b": "MP12207A_B",
  "mp12207": "MP12207A_B",
  "mp12207a_b_i": "MP12207A_B_I",
  "m p12207 a  b  i": "MP12207A_B_I",
  "mp12207a_b_p": "MP12207A_B_P",
  "m p12207 a  b  p": "MP12207A_B_P",
  "mp13019a_b": "MP13019A_B",
  "m p13019 a  b": "MP13019A_B",
  "mp13019": "MP13019A_B",
  "mp13019a_b_i": "MP13019A_B_I",
  "m p13019 a  b  i": "MP13019A_B_I",
  "mp13019a_b_p": "MP13019A_B_P",
  "m p13019 a  b  p": "MP13019A_B_P",
  "mp13023a_b": "MP13023A_B",
  "m p13023 a  b": "MP13023A_B",
  "mp13023": "MP13023A_B",
  "mp13023a_b_i": "MP13023A_B_I",
  "m p13023 a  b  i": "MP13023A_B_I",
  "mp13023a_b_p": "MP13023A_B_P",
  "m p13023 a  b  p": "MP13023A_B_P",
  "mp13026a_b": "MP13026A_B",
  "m p13026 a  b": "MP13026A_B",
  "mp13026": "MP13026A_B",
  "mp13026a_b_i": "MP13026A_B_I",
  "m p13026 a  b  i": "MP13026A_B_I",
  "mp13026a_b_p": "MP13026A_B_P",
  "m p13026 a  b  p": "MP13026A_B_P",
  "mp13029a_b": "MP13029A_B",
  "m p13029 a  b": "MP13029A_B",
  "mp13029": "MP13029A_B",
  "mp13029a_b_i": "MP13029A_B_I",
  "m p13029 a  b  i": "MP13029A_B_I",
  "mp13029a_b_p": "MP13029A_B_P",
  "m p13029 a  b  p": "MP13029A_B_P",
  "mp14029a_b": "MP14029A_B",
  "m p14029 a  b": "MP14029A_B",
  "mp14029": "MP14029A_B",
  "mp14029a_b_i": "MP14029A_B_I",
  "m p14029 a  b  i": "MP14029A_B_I",
  "mp14029a_b_p": "MP14029A_B_P",
  "m p14029 a  b  p": "MP14029A_B_P",
  "mp28591a_b": "MP28591A_B",
  "m p28591 a  b": "MP28591A_B",
  "mp28591": "MP28591A_B",
  "mp28591a_b_i": "MP28591A_B_I",
  "m p28591 a  b  i": "MP28591A_B_I",
  "mp28591a_b_p": "MP28591A_B_P",
  "m p28591 a  b  p": "MP28591A_B_P",
  "mp28646a_b": "MP28646A_B",
  "m p28646 a  b": "MP28646A_B",
  "mp28646": "MP28646A_B",
  "mp28646a_b_i": "MP28646A_B_I",
  "m p28646 a  b  i": "MP28646A_B_I",
  "mp28646a_b_p": "MP28646A_B_P",
  "m p28646 a  b  p": "MP28646A_B_P",
  // === X CODES (Spending/Economic Data) ===
  "x14058_x": "X14058_X",
  "x14058  x": "X14058_X",
  "x14058_x_a": "X14058_X_A",
  "x14058  x  a": "X14058_X_A",
  "x14060_x": "X14060_X",
  "x14060  x": "X14060_X",
  "x14060_x_a": "X14060_X_A",
  "x14060  x  a": "X14060_X_A",
  "x14068_x": "X14068_X",
  "x14068  x": "X14068_X",
  "x14068_x_a": "X14068_X_A",
  "x14068  x  a": "X14068_X_A",
  // === GENERATION DEMOGRAPHICS ===
  "genalphacy": "GENALPHACY",
  "g e n a l p h a c y": "GENALPHACY",
  "generation alpha": "GENALPHACY",
  "gen alpha": "GENALPHACY",
  "genalphacy_p": "GENALPHACY_P",
  "g e n a l p h a c y  p": "GENALPHACY_P",
  "genalphafy": "GENALPHAFY",
  "g e n a l p h a f y": "GENALPHAFY",
  "genalphafy_p": "GENALPHAFY_P",
  "g e n a l p h a f y  p": "GENALPHAFY_P",
  "genz_cy": "GENZ_CY",
  "g e n z  c y": "GENZ_CY",
  "generation z": "GENZ_CY",
  "gen z": "GENZ_CY",
  "genz": "GENZ_CY",
  "genz_cy_p": "GENZ_CY_P",
  "g e n z  c y  p": "GENZ_CY_P",
  "genz_fy": "GENZ_FY",
  "g e n z  f y": "GENZ_FY",
  "genz_fy_p": "GENZ_FY_P",
  "g e n z  f y  p": "GENZ_FY_P",
  // === LOCATION FIELDS ===
  "latitude": "LATITUDE",
  "l a t i t u d e": "LATITUDE",
  "longitude": "LONGITUDE",
  "l o n g i t u d e": "LONGITUDE",
  "postal code": "postcode",
  // === NATURAL LANGUAGE ALIASES ===
  "people": "GENALPHACY",
  "residents": "GENALPHACY",
  "demographics": "GENALPHACY",
  "young": "GENZ_CY_P",
  "younger": "GENZ_CY_P",
  "youth": "GENZ_CY_P",
  "location": "DESCRIPTION"
};

export const fieldAliases = FIELD_ALIASES;