/**
 * California state configuration — stub.
 *
 * Data paths point to /data/political/california/ which will be populated
 * once the client delivers the CA precinct data. All boundary layers are
 * marked hasData: false until the files arrive.
 *
 * To activate: set ACTIVE_STATE=california in .env.local
 */

import type { StateConfig } from '@/types/stateConfig';

const CA = '/data/political/california';
const PRECINCTS = `${CA}/precincts`;
const DISTRICTS = `${CA}/districts`;
const BLOCK_GROUPS = `${CA}/block-groups`;
const CENSUS_TRACTS = `${CA}/census-tracts`;

export const californiaConfig: StateConfig = {
  name: 'California',
  abbreviation: 'CA',
  fips: '06',
  defaultCounty: 'Statewide',
  summaryAreaName: 'California',

  map: {
    defaultCenter: [-119.4179, 36.7783],
    defaultZoom: 6,
    jurisdictionCentroids: {
      los_angeles: [-118.2437, 34.0522],
      san_francisco: [-122.4194, 37.7749],
      san_diego: [-117.1611, 32.7157],
      sacramento: [-121.4944, 38.5816],
      san_jose: [-121.8863, 37.3382],
      fresno: [-119.7871, 36.7378],
      long_beach: [-118.1937, 33.7701],
      oakland: [-122.2712, 37.8044],
      bakersfield: [-119.0187, 35.3733],
      anaheim: [-117.9145, 33.8366],
    },
  },

  paths: {
    precinctBoundaries: `${PRECINCTS}/ca_precincts.geojson`,
    electionResults: `${PRECINCTS}/ca_precinct_election_history.json`,
    targetingScores: `${PRECINCTS}/precinct_targeting_scores.json`,
    districtCrosswalk: `${PRECINCTS}/ca_precinct_district_crosswalk.json`,
    politicalScores: '/data/processed/precinct_political_scores.json',
    demographics: '/data/processed/precinct_ba_demographics.json',
    precinctDemographics: `${PRECINCTS}/ca_precinct_demographics.json`,
    crosswalk: '/data/processed/precinct_blockgroup_crosswalk.json',
    h3Aggregates: '/data/processed/h3_aggregates.json',
    h3GeoJSON: '/data/processed/h3_aggregates.geojson',
    stateH3Aggregates: `${PRECINCTS}/ca_h3_aggregates.json`,
    stateH3GeoJSON: `${PRECINCTS}/ca_h3_aggregates.geojson`,
  },

  blobKeys: {
    precinctBoundaries: 'political/precincts/ca_precincts',
    electionResults: 'political/elections/ca_precinct_results',
    targetingScores: 'political/targeting/precinct_scores',
    politicalScores: 'political/targeting/political_scores',
    demographics: 'political/demographics/precinct_ba',
    crosswalk: 'political/crosswalk/precinct_blockgroup',
    districtCrosswalk: 'political/crosswalk/ca_precinct_districts',
    h3Aggregates: 'political/h3/aggregates',
    h3GeoJSON: 'political/h3/aggregates_geojson',
    stateH3Aggregates: 'political/h3/ca_aggregates',
    stateH3GeoJSON: 'political/h3/ca_aggregates_geojson',
    modelRegistry: 'political/models/registry',
  },

  countyFips: {
    '001': 'Alameda',
    '003': 'Alpine',
    '005': 'Amador',
    '007': 'Butte',
    '009': 'Calaveras',
    '011': 'Colusa',
    '013': 'Contra Costa',
    '015': 'Del Norte',
    '017': 'El Dorado',
    '019': 'Fresno',
    '021': 'Glenn',
    '023': 'Humboldt',
    '025': 'Imperial',
    '027': 'Inyo',
    '029': 'Kern',
    '031': 'Kings',
    '033': 'Lake',
    '035': 'Lassen',
    '037': 'Los Angeles',
    '039': 'Madera',
    '041': 'Marin',
    '043': 'Mariposa',
    '045': 'Mendocino',
    '047': 'Merced',
    '049': 'Modoc',
    '051': 'Mono',
    '053': 'Monterey',
    '055': 'Napa',
    '057': 'Nevada',
    '059': 'Orange',
    '061': 'Placer',
    '063': 'Plumas',
    '065': 'Riverside',
    '067': 'Sacramento',
    '069': 'San Benito',
    '071': 'San Bernardino',
    '073': 'San Diego',
    '075': 'San Francisco',
    '077': 'San Joaquin',
    '079': 'San Luis Obispo',
    '081': 'San Mateo',
    '083': 'Santa Barbara',
    '085': 'Santa Clara',
    '087': 'Santa Cruz',
    '089': 'Shasta',
    '091': 'Sierra',
    '093': 'Siskiyou',
    '095': 'Solano',
    '097': 'Sonoma',
    '099': 'Stanislaus',
    '101': 'Sutter',
    '103': 'Tehama',
    '105': 'Trinity',
    '107': 'Tulare',
    '109': 'Tuolumne',
    '111': 'Ventura',
    '113': 'Yolo',
    '115': 'Yuba',
  },

  boundaryLayers: {
    precinct: {
      type: 'precinct',
      displayName: 'Precinct',
      pluralName: 'Precincts',
      source: 'California election results',
      idField: 'UNIQUE_ID',
      nameField: 'NAME',
      dataPath: `${PRECINCTS}/ca_precincts.geojson`,
      color: '#6366f1',
      hasData: false,
    },
    h3: {
      type: 'h3',
      displayName: 'H3 Hex (res 7)',
      pluralName: 'H3 Hex Cells',
      source: 'Aggregated from precinct centroids',
      idField: 'h3_index',
      nameField: 'h3_index',
      dataPath: `${PRECINCTS}/ca_h3_aggregates.geojson`,
      color: '#a855f7',
      hasData: false,
    },
    'zip-code': {
      type: 'zip-code',
      displayName: 'ZIP Code',
      pluralName: 'ZIP Codes',
      source: 'U.S. Census Bureau / CA GIS',
      idField: 'ZIP_CODE',
      nameField: 'ZIP_CODE',
      dataPath: `${DISTRICTS}/ca_zip_codes.geojson`,
      color: '#8b5cf6',
      hasData: false,
    },
    'block-group': {
      type: 'block-group',
      displayName: 'Block Group',
      pluralName: 'Block Groups',
      source: 'U.S. Census Bureau',
      idField: 'GEOID',
      nameField: 'NAMELSAD',
      dataPath: `${BLOCK_GROUPS}/ca_block_groups.part000.geojson`,
      color: '#06b6d4',
      hasData: false,
    },
    'census-tract': {
      type: 'census-tract',
      displayName: 'Census Tract',
      pluralName: 'Census Tracts',
      source: 'U.S. Census Bureau',
      idField: 'GEOID',
      nameField: 'NAMELSAD',
      dataPath: `${CENSUS_TRACTS}/ca_census_tracts.geojson`,
      color: '#14b8a6',
      hasData: false,
    },
    'state-house': {
      type: 'state-house',
      displayName: 'State Assembly District',
      pluralName: 'State Assembly Districts',
      source: 'California legislative boundaries',
      idField: 'DISTRICT',
      nameField: 'DISTRICT',
      dataPath: `${DISTRICTS}/ca_state_assembly.geojson`,
      color: '#f59e0b',
      hasData: false,
    },
    'state-senate': {
      type: 'state-senate',
      displayName: 'State Senate District',
      pluralName: 'State Senate Districts',
      source: 'California legislative boundaries',
      idField: 'DISTRICT',
      nameField: 'DISTRICT',
      dataPath: `${DISTRICTS}/ca_state_senate.geojson`,
      color: '#ef4444',
      hasData: false,
    },
    congressional: {
      type: 'congressional',
      displayName: 'Congressional District',
      pluralName: 'Congressional Districts',
      source: 'U.S. Census Bureau / CA congressional boundaries',
      idField: 'DISTRICT',
      nameField: 'DISTRICT',
      dataPath: `${DISTRICTS}/ca_congressional.geojson`,
      color: '#3b82f6',
      hasData: false,
    },
    municipality: {
      type: 'municipality',
      displayName: 'City/Municipality',
      pluralName: 'Cities & Municipalities',
      source: 'California GIS / Census Places',
      idField: 'GEOID',
      nameField: 'NAME',
      dataPath: `${DISTRICTS}/ca_municipalities.geojson`,
      color: '#22c55e',
      hasData: false,
    },
    township: {
      type: 'township',
      displayName: 'City/Town',
      pluralName: 'Cities & Towns',
      source: 'California GIS / Census Places',
      idField: 'GEOID',
      nameField: 'NAME',
      dataPath: `${DISTRICTS}/ca_municipalities.geojson`,
      color: '#84cc16',
      hasData: false,
    },
    'school-district': {
      type: 'school-district',
      displayName: 'School District',
      pluralName: 'School Districts',
      source: 'California Department of Education / GIS',
      idField: 'GEOID',
      nameField: 'NAME',
      dataPath: `${DISTRICTS}/ca_school_districts.geojson`,
      color: '#f97316',
      hasData: false,
    },
  },

  entities: [
    { name: 'california', level: 'state', aliases: ['ca', 'the golden state'] },
    { name: 'los angeles', level: 'city', parent: 'los angeles county', aliases: ['la', 'l.a.'] },
    { name: 'san francisco', level: 'city', parent: 'san francisco county', aliases: ['sf', 's.f.', 'the city'] },
    { name: 'san diego', level: 'city', parent: 'san diego county' },
    { name: 'sacramento', level: 'city', parent: 'sacramento county' },
    { name: 'san jose', level: 'city', parent: 'santa clara county' },
    { name: 'fresno', level: 'city', parent: 'fresno county' },
    { name: 'long beach', level: 'city', parent: 'los angeles county' },
    { name: 'oakland', level: 'city', parent: 'alameda county' },
    { name: 'bakersfield', level: 'city', parent: 'kern county' },
    { name: 'anaheim', level: 'city', parent: 'orange county' },
    { name: 'stockton', level: 'city', parent: 'san joaquin county' },
    { name: 'riverside', level: 'city', parent: 'riverside county' },
    { name: 'los angeles county', level: 'county', parent: 'california', aliases: ['la county'] },
    { name: 'san diego county', level: 'county', parent: 'california' },
    { name: 'orange county', level: 'county', parent: 'california', aliases: ['the oc'] },
    { name: 'riverside county', level: 'county', parent: 'california' },
    { name: 'san bernardino county', level: 'county', parent: 'california' },
    { name: 'santa clara county', level: 'county', parent: 'california', aliases: ['silicon valley'] },
    { name: 'alameda county', level: 'county', parent: 'california' },
    { name: 'sacramento county', level: 'county', parent: 'california' },
    { name: 'contra costa county', level: 'county', parent: 'california' },
    { name: 'fresno county', level: 'county', parent: 'california' },
    { name: 'kern county', level: 'county', parent: 'california' },
    { name: 'san francisco county', level: 'county', parent: 'california' },
    { name: 'ventura county', level: 'county', parent: 'california' },
    { name: 'san mateo county', level: 'county', parent: 'california' },
    { name: 'san joaquin county', level: 'county', parent: 'california' },
    { name: 'stanislaus county', level: 'county', parent: 'california' },
    { name: 'sonoma county', level: 'county', parent: 'california' },
  ],

  elections: {
    primaryDate: '2026-06-02',
    primaryType: 'semi-closed',
    generalDate: '2026-11-03',
    voterRegistrationDeadline: '2026-10-19',
    earlyVotingStart: '2026-10-05',
    earlyVotingEnd: '2026-11-03',
    absenteeRequestDeadline: '2026-10-27',
  },

  display: {
    pageTitle: 'MPIQ - CA',
  },
};
