/**
 * Pennsylvania state configuration.
 *
 * All PA-specific values live here. To update PA data or paths, edit this file.
 * To switch the active state, change lib/config/activeState.ts.
 */

import type { StateConfig } from '@/types/stateConfig';

const PA = '/data/political/pensylvania'; // typo preserved — matches public/ folder name
const PRECINCTS = `${PA}/precincts`;
const DISTRICTS = `${PA}/districts`;
const BLOCK_GROUPS = `${PA}/block-groups`;
const CENSUS_TRACTS = `${PA}/census-tracts`;

export const pennsylvaniaConfig: StateConfig = {
  name: 'Pennsylvania',
  abbreviation: 'PA',
  fips: '42',
  defaultCounty: 'Statewide',
  summaryAreaName: 'Pennsylvania',

  map: {
    defaultCenter: [-77.194, 41.203],
    defaultZoom: 7,
    jurisdictionCentroids: {
      philadelphia: [-75.1652, 39.9526],
      pittsburgh: [-79.9959, 40.4406],
      allentown: [-75.4902, 40.6023],
      erie: [-80.0851, 42.1292],
      reading: [-75.9268, 40.3356],
      scranton: [-75.6624, 41.4085],
      harrisburg: [-76.8844, 40.2732],
    },
  },

  paths: {
    precinctBoundaries: `${PRECINCTS}/pa_2020_presidential.geojson`,
    electionResults: `${PRECINCTS}/pa_precinct_election_history.json`,
    targetingScores: `${PRECINCTS}/precinct_targeting_scores.json`,
    districtCrosswalk: `${PRECINCTS}/pa_precinct_district_crosswalk.json`,
    politicalScores: '/data/processed/precinct_political_scores.json',
    demographics: '/data/processed/precinct_ba_demographics.json',
    precinctDemographics: `${PRECINCTS}/pa_precinct_demographics.json`,
    crosswalk: '/data/processed/precinct_blockgroup_crosswalk.json',
    h3Aggregates: '/data/processed/h3_aggregates.json',
    h3GeoJSON: '/data/processed/h3_aggregates.geojson',
    stateH3Aggregates: `${PRECINCTS}/pa_h3_aggregates.json`,
    stateH3GeoJSON: `${PRECINCTS}/pa_h3_aggregates.geojson`,
    demographicLayersDir: `${PA}/demographics/PA_Demographics_2025`,
  },

  blobKeys: {
    precinctBoundaries: 'political/precincts/pa_2020_presidential',
    electionResults: 'political/elections/pa_precinct_results',
    targetingScores: 'political/targeting/precinct_scores',
    politicalScores: 'political/targeting/political_scores',
    demographics: 'political/demographics/precinct_ba',
    crosswalk: 'political/crosswalk/precinct_blockgroup',
    districtCrosswalk: 'political/crosswalk/pa_precinct_districts',
    h3Aggregates: 'political/h3/aggregates',
    h3GeoJSON: 'political/h3/aggregates_geojson',
    stateH3Aggregates: 'political/h3/pa_aggregates',
    stateH3GeoJSON: 'political/h3/pa_aggregates_geojson',
    modelRegistry: 'political/models/registry',
  },

  countyFips: {
    '001': 'Adams',
    '003': 'Allegheny',
    '005': 'Armstrong',
    '007': 'Beaver',
    '009': 'Bedford',
    '011': 'Berks',
    '013': 'Blair',
    '015': 'Bradford',
    '017': 'Bucks',
    '019': 'Butler',
    '021': 'Cambria',
    '023': 'Cameron',
    '025': 'Carbon',
    '027': 'Centre',
    '029': 'Chester',
    '031': 'Clarion',
    '033': 'Clearfield',
    '035': 'Clinton',
    '037': 'Columbia',
    '039': 'Crawford',
    '041': 'Cumberland',
    '043': 'Dauphin',
    '045': 'Delaware',
    '047': 'Elk',
    '049': 'Erie',
    '051': 'Fayette',
    '053': 'Forest',
    '055': 'Franklin',
    '057': 'Fulton',
    '059': 'Greene',
    '061': 'Huntingdon',
    '063': 'Indiana',
    '065': 'Jefferson',
    '067': 'Juniata',
    '069': 'Lackawanna',
    '071': 'Lancaster',
    '073': 'Lawrence',
    '075': 'Lebanon',
    '077': 'Lehigh',
    '079': 'Luzerne',
    '081': 'Lycoming',
    '083': 'McKean',
    '085': 'Mercer',
    '087': 'Mifflin',
    '089': 'Monroe',
    '091': 'Montgomery',
    '093': 'Montour',
    '095': 'Northampton',
    '097': 'Northumberland',
    '099': 'Perry',
    '101': 'Philadelphia',
    '103': 'Pike',
    '105': 'Potter',
    '107': 'Schuylkill',
    '109': 'Snyder',
    '111': 'Somerset',
    '113': 'Sullivan',
    '115': 'Susquehanna',
    '117': 'Tioga',
    '119': 'Union',
    '121': 'Venango',
    '123': 'Warren',
    '125': 'Washington',
    '127': 'Wayne',
    '129': 'Westmoreland',
    '131': 'Wyoming',
    '133': 'York',
  },

  boundaryLayers: {
    precinct: {
      type: 'precinct',
      displayName: 'Precinct',
      pluralName: 'Precincts',
      source: 'Pennsylvania election results (2020 presidential)',
      idField: 'UNIQUE_ID',
      nameField: 'NAME',
      dataPath: `${PRECINCTS}/pa_2020_presidential.geojson`,
      color: '#6366f1',
      hasData: true,
    },
    h3: {
      type: 'h3',
      displayName: 'H3 Hex (res 7)',
      pluralName: 'H3 Hex Cells',
      source: 'Aggregated from precinct centroids (build-pa-h3-aggregates)',
      idField: 'h3_index',
      nameField: 'h3_index',
      dataPath: `${PRECINCTS}/pa_h3_aggregates.geojson`,
      color: '#a855f7',
      hasData: false,
    },
    'zip-code': {
      type: 'zip-code',
      displayName: 'ZIP Code',
      pluralName: 'ZIP Codes',
      source: 'U.S. Census Bureau / PA GIS',
      idField: 'ZIP_CODE',
      nameField: 'ZIP_CODE',
      dataPath: `${DISTRICTS}/pa_zip_codes.geojson`,
      color: '#8b5cf6',
      hasData: true,
    },
    'block-group': {
      type: 'block-group',
      displayName: 'Block Group',
      pluralName: 'Block Groups',
      source: 'U.S. Census Bureau',
      idField: 'GEOID',
      nameField: 'NAMELSAD',
      dataPath: `${BLOCK_GROUPS}/pa_block_groups.part000.geojson`,
      dataPaths: [
        `${BLOCK_GROUPS}/pa_block_groups.part000.geojson`,
        `${BLOCK_GROUPS}/pa_block_groups.part001.geojson`,
      ],
      color: '#06b6d4',
      hasData: true,
    },
    'census-tract': {
      type: 'census-tract',
      displayName: 'Census Tract',
      pluralName: 'Census Tracts',
      source: 'U.S. Census Bureau',
      idField: 'GEOID',
      nameField: 'NAMELSAD',
      dataPath: `${CENSUS_TRACTS}/pa_census_tracts.geojson`,
      color: '#14b8a6',
      hasData: true,
    },
    'state-house': {
      type: 'state-house',
      displayName: 'State House District',
      pluralName: 'State House Districts',
      source: 'Pennsylvania legislative boundaries',
      idField: 'LEG_DISTRI',
      nameField: 'LEG_DISTRI',
      dataPath: `${DISTRICTS}/pa_state_house.geojson`,
      color: '#f59e0b',
      hasData: true,
    },
    'state-senate': {
      type: 'state-senate',
      displayName: 'State Senate District',
      pluralName: 'State Senate Districts',
      source: 'Pennsylvania legislative boundaries',
      idField: 'LEG_DISTRI',
      nameField: 'LEG_DISTRI',
      dataPath: `${DISTRICTS}/pa_state_senate.geojson`,
      color: '#ef4444',
      hasData: true,
    },
    congressional: {
      type: 'congressional',
      displayName: 'Congressional District',
      pluralName: 'Congressional Districts',
      source: 'U.S. Census Bureau / PA congressional boundaries',
      idField: 'LEG_DISTRI',
      nameField: 'LEG_DISTRI',
      dataPath: `${DISTRICTS}/pa_congressional.geojson`,
      color: '#3b82f6',
      hasData: true,
    },
    municipality: {
      type: 'municipality',
      displayName: 'Municipality',
      pluralName: 'Municipalities',
      source: 'PA DCED / municipal GIS',
      idField: 'GEOID',
      nameField: 'MUNICIPAL1',
      dataPath: `${DISTRICTS}/pa_municipalities.geojson`,
      color: '#22c55e',
      hasData: true,
    },
    township: {
      type: 'township',
      displayName: 'Township/City',
      pluralName: 'Townships & Cities',
      source: 'PA DCED / municipal GIS',
      idField: 'GEOID',
      nameField: 'MUNICIPAL1',
      dataPath: `${DISTRICTS}/pa_municipalities.geojson`,
      color: '#84cc16',
      hasData: false,
    },
    'school-district': {
      type: 'school-district',
      displayName: 'School District',
      pluralName: 'School Districts',
      source: 'Pennsylvania Department of Education / GIS',
      idField: 'AUN_NUM',
      nameField: 'SCHOOL_NAM',
      dataPath: `${DISTRICTS}/pa_school_districts.geojson`,
      color: '#f97316',
      hasData: true,
    },
  },

  entities: [
    { name: 'pennsylvania', level: 'state', aliases: ['pa', 'the commonwealth'] },
    { name: 'philadelphia', level: 'city', parent: 'pennsylvania', aliases: ['philly'] },
    { name: 'pittsburgh', level: 'city', parent: 'pennsylvania' },
    { name: 'harrisburg', level: 'city', parent: 'pennsylvania' },
    { name: 'allentown', level: 'city', parent: 'pennsylvania' },
    { name: 'erie', level: 'city', parent: 'pennsylvania' },
    { name: 'reading', level: 'city', parent: 'pennsylvania' },
    { name: 'scranton', level: 'city', parent: 'pennsylvania' },
    { name: 'philadelphia county', level: 'county', parent: 'pennsylvania' },
    { name: 'allegheny county', level: 'county', parent: 'pennsylvania', aliases: ['allegheny'] },
    { name: 'montgomery county', level: 'county', parent: 'pennsylvania', aliases: ['montco'] },
    { name: 'bucks county', level: 'county', parent: 'pennsylvania' },
    { name: 'delaware county', level: 'county', parent: 'pennsylvania', aliases: ['delco'] },
    { name: 'chester county', level: 'county', parent: 'pennsylvania' },
    { name: 'lancaster county', level: 'county', parent: 'pennsylvania' },
    { name: 'york county', level: 'county', parent: 'pennsylvania' },
    { name: 'dauphin county', level: 'county', parent: 'pennsylvania' },
    { name: 'luzerne county', level: 'county', parent: 'pennsylvania' },
    { name: 'lackawanna county', level: 'county', parent: 'pennsylvania' },
    { name: 'berks county', level: 'county', parent: 'pennsylvania' },
    { name: 'lehigh county', level: 'county', parent: 'pennsylvania' },
    { name: 'northampton county', level: 'county', parent: 'pennsylvania' },
    { name: 'westmoreland county', level: 'county', parent: 'pennsylvania' },
    { name: 'erie county', level: 'county', parent: 'pennsylvania' },
    { name: 'centre county', level: 'county', parent: 'pennsylvania' },
    { name: 'cumberland county', level: 'county', parent: 'pennsylvania' },
  ],

  elections: {
    primaryDate: '2026-05-19',
    primaryType: 'closed',
    generalDate: '2026-11-03',
    voterRegistrationDeadline: '2026-10-19',
    earlyVotingStart: '2026-10-24',
    earlyVotingEnd: '2026-11-02',
    absenteeRequestDeadline: '2026-10-27',
  },

  display: {
    pageTitle: 'MPIQ - PA',
    compareExample: 'Compare Philadelphia to Pittsburgh',
    stateLowerChamberLabel: 'State House Districts',
  },
};
